services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    networks:
      - xschat-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  rabbitmq:
    image: rabbitmq:4.0.8-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672" # RabbitMQ 管理界面
      - "5672:5672"   # RabbitMQ 连接端口
    networks:
      - xschat-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xs-chat-backend
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - xschat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

networks:
  xschat-network:
    driver: bridge
